///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace ModuleLibrary.Recording_modules.Database
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The CountNumberOfEntries recording.
    /// </summary>
    [TestModule("85e363ef-68b0-4953-9a15-50218604f3df", ModuleType.Recording, 1)]
    public partial class CountNumberOfEntries : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::ModuleLibrary.ModuleLibraryRepository repository.
        /// </summary>
        public static global::ModuleLibrary.ModuleLibraryRepository repo = global::ModuleLibrary.ModuleLibraryRepository.Instance;

        static CountNumberOfEntries instance = new CountNumberOfEntries();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public CountNumberOfEntries()
        {
            varEntryCount = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static CountNumberOfEntries Instance
        {
            get { return instance; }
        }

#region Variables

        string _varEntryCount;

        /// <summary>
        /// Gets or sets the value of variable varEntryCount.
        /// </summary>
        [TestVariable("9b22cac5-bdda-4262-a556-e1189856297e")]
        public string varEntryCount
        {
            get { return _varEntryCount; }
            set { _varEntryCount = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            // Reads number of entries and copies value to variable
            Report.Log(ReportLevel.Info, "Get Value", "Reads number of entries and copies value to variable\r\nGetting attribute 'Text' from item 'RXDemoApplication.Test_database_panel.LblDatabaseCounter' and assigning its value to variable 'varEntryCount'.", repo.RXDemoApplication.Test_database_panel.LblDatabaseCounterInfo, new RecordItemIndex(0));
            varEntryCount = repo.RXDemoApplication.Test_database_panel.LblDatabaseCounter.Element.GetAttributeValueText("Text");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
