///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace ModuleLibrary.Recording_modules.Database
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The InsertLastName recording.
    /// </summary>
    [TestModule("d991f0a2-ebbb-4339-9f4d-5fa49a850147", ModuleType.Recording, 1)]
    public partial class InsertLastName : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::ModuleLibrary.ModuleLibraryRepository repository.
        /// </summary>
        public static global::ModuleLibrary.ModuleLibraryRepository repo = global::ModuleLibrary.ModuleLibraryRepository.Instance;

        static InsertLastName instance = new InsertLastName();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public InsertLastName()
        {
            varLastName = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static InsertLastName Instance
        {
            get { return instance; }
        }

#region Variables

        string _varLastName;

        /// <summary>
        /// Gets or sets the value of variable varLastName.
        /// </summary>
        [TestVariable("8d552d09-36c1-4e67-b794-7d873bd8aac7")]
        public string varLastName
        {
            get { return _varLastName; }
            set { _varLastName = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Set value", "Setting attribute Text to '$varLastName' on item 'RXDemoApplication.Test_database_panel.Form_fields.TxtLastName'.", repo.RXDemoApplication.Test_database_panel.Form_fields.TxtLastNameInfo, new RecordItemIndex(0));
            repo.RXDemoApplication.Test_database_panel.Form_fields.TxtLastName.Element.SetAttributeValue("Text", varLastName);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
