///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace ModuleLibrary.Recording_modules.Database
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The InsertAge recording.
    /// </summary>
    [TestModule("59b64c51-f2f9-4a55-8302-629b7f3cae60", ModuleType.Recording, 1)]
    public partial class InsertAge : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::ModuleLibrary.ModuleLibraryRepository repository.
        /// </summary>
        public static global::ModuleLibrary.ModuleLibraryRepository repo = global::ModuleLibrary.ModuleLibraryRepository.Instance;

        static InsertAge instance = new InsertAge();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public InsertAge()
        {
            varAge = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static InsertAge Instance
        {
            get { return instance; }
        }

#region Variables

        string _varAge;

        /// <summary>
        /// Gets or sets the value of variable varAge.
        /// </summary>
        [TestVariable("b17bacdd-2acb-4927-8a8a-4afc4d15cb98")]
        public string varAge
        {
            get { return _varAge; }
            set { _varAge = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Set value", "Setting attribute Text to '$varAge' on item 'RXDemoApplication.Test_database_panel.Form_fields.TxtAge'.", repo.RXDemoApplication.Test_database_panel.Form_fields.TxtAgeInfo, new RecordItemIndex(0));
            repo.RXDemoApplication.Test_database_panel.Form_fields.TxtAge.Element.SetAttributeValue("Text", varAge);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
