///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace ModuleLibrary.Recording_modules.Database
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The ValidateCounter recording.
    /// </summary>
    [TestModule("247de62c-8b79-44f6-89f8-407b01ef3aac", ModuleType.Recording, 1)]
    public partial class ValidateCounter : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::ModuleLibrary.ModuleLibraryRepository repository.
        /// </summary>
        public static global::ModuleLibrary.ModuleLibraryRepository repo = global::ModuleLibrary.ModuleLibraryRepository.Instance;

        static ValidateCounter instance = new ValidateCounter();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public ValidateCounter()
        {
            varCounter = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static ValidateCounter Instance
        {
            get { return instance; }
        }

#region Variables

        string _varCounter;

        /// <summary>
        /// Gets or sets the value of variable varCounter.
        /// </summary>
        [TestVariable("3cc92b60-8f8e-4170-ae34-a3310abbb49b")]
        public string varCounter
        {
            get { return _varCounter; }
            set { _varCounter = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 0;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 0.00;

            Init();

            // Parametrized validation of database counter
            Report.Log(ReportLevel.Info, "Validation", "Parametrized validation of database counter\r\nValidating AttributeEqual (Text=$varCounter) on item 'RXDemoApplication.Test_database_panel.LblDatabaseCounter'.", repo.RXDemoApplication.Test_database_panel.LblDatabaseCounterInfo, new RecordItemIndex(0));
            Validate.AttributeEqual(repo.RXDemoApplication.Test_database_panel.LblDatabaseCounterInfo, "Text", varCounter);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
