///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace ModuleLibrary
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the ModuleLibraryRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("c734fd40-ff24-428a-afb1-d0cc1c4cdd1a")]
    public partial class ModuleLibraryRepository : RepoGenBaseFolder
    {
        static ModuleLibraryRepository instance = new ModuleLibraryRepository();
        ModuleLibraryRepositoryFolders.RXDemoApplicationAppFolder _rxdemoapplication;
        ModuleLibraryRepositoryFolders.DepartmentListAppFolder _departmentlist;
        ModuleLibraryRepositoryFolders.RxDemoAppAboutInfoAppFolder _rxdemoappaboutinfo;

        /// <summary>
        /// Gets the singleton class instance representing the ModuleLibraryRepository element repository.
        /// </summary>
        [RepositoryFolder("c734fd40-ff24-428a-afb1-d0cc1c4cdd1a")]
        public static ModuleLibraryRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public ModuleLibraryRepository() 
            : base("ModuleLibraryRepository", "/", null, 0, false, "c734fd40-ff24-428a-afb1-d0cc1c4cdd1a", ".\\RepositoryImages\\ModuleLibraryRepositoryc734fd40.rximgres")
        {
            _rxdemoapplication = new ModuleLibraryRepositoryFolders.RXDemoApplicationAppFolder(this);
            _departmentlist = new ModuleLibraryRepositoryFolders.DepartmentListAppFolder(this);
            _rxdemoappaboutinfo = new ModuleLibraryRepositoryFolders.RxDemoAppAboutInfoAppFolder(this);
        }

#region Variables

        string _varRegister = "Introduction";

        /// <summary>
        /// Gets or sets the value of variable varRegister.
        /// </summary>
        [TestVariable("1494ba44-4ec7-43fb-be5a-9042db4cda73")]
        public string varRegister
        {
            get { return _varRegister; }
            set { _varRegister = value; }
        }

        string _varDepartment = "";

        /// <summary>
        /// Gets or sets the value of variable varDepartment.
        /// </summary>
        [TestVariable("f84c048f-7fee-4157-a639-03dc5786b7ec")]
        public string varDepartment
        {
            get { return _varDepartment; }
            set { _varDepartment = value; }
        }

        string _varGender = "";

        /// <summary>
        /// Gets or sets the value of variable varGender.
        /// </summary>
        [TestVariable("febf3128-3b96-4fe7-8605-a9fa65f4b1f0")]
        public string varGender
        {
            get { return _varGender; }
            set { _varGender = value; }
        }

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("c734fd40-ff24-428a-afb1-d0cc1c4cdd1a")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The RXDemoApplication folder.
        /// </summary>
        [RepositoryFolder("d59907b2-f23c-4d39-b364-e7e3e0d9ce81")]
        public virtual ModuleLibraryRepositoryFolders.RXDemoApplicationAppFolder RXDemoApplication
        {
            get { return _rxdemoapplication; }
        }

        /// <summary>
        /// The DepartmentList folder.
        /// </summary>
        [RepositoryFolder("09bcc6f7-9fe6-4896-b1c9-7dd8d01b68ac")]
        public virtual ModuleLibraryRepositoryFolders.DepartmentListAppFolder DepartmentList
        {
            get { return _departmentlist; }
        }

        /// <summary>
        /// The RxDemoAppAboutInfo folder.
        /// </summary>
        [RepositoryFolder("3b5e59b2-3bcc-4a32-a4aa-281bb2c188b0")]
        public virtual ModuleLibraryRepositoryFolders.RxDemoAppAboutInfoAppFolder RxDemoAppAboutInfo
        {
            get { return _rxdemoappaboutinfo; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class ModuleLibraryRepositoryFolders
    {
        /// <summary>
        /// The RXDemoApplicationAppFolder folder.
        /// </summary>
        [RepositoryFolder("d59907b2-f23c-4d39-b364-e7e3e0d9ce81")]
        public partial class RXDemoApplicationAppFolder : RepoGenBaseFolder
        {
            ModuleLibraryRepositoryFolders.Register_panelsFolder _register_panels;
            ModuleLibraryRepositoryFolders.Test_database_panelFolder _test_database_panel;
            ModuleLibraryRepositoryFolders.Main_menuFolder _main_menu;

            /// <summary>
            /// Creates a new RXDemoApplication  folder.
            /// </summary>
            public RXDemoApplicationAppFolder(RepoGenBaseFolder parentFolder) :
                    base("RXDemoApplication", "/form[@controlname='RxMainFrame']", parentFolder, 30000, null, true, "d59907b2-f23c-4d39-b364-e7e3e0d9ce81", "")
            {
                _register_panels = new ModuleLibraryRepositoryFolders.Register_panelsFolder(this);
                _test_database_panel = new ModuleLibraryRepositoryFolders.Test_database_panelFolder(this);
                _main_menu = new ModuleLibraryRepositoryFolders.Main_menuFolder(this);
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("d59907b2-f23c-4d39-b364-e7e3e0d9ce81")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("d59907b2-f23c-4d39-b364-e7e3e0d9ce81")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Register_panels folder.
            /// </summary>
            [RepositoryFolder("9b9f04c1-9c82-4ed5-b9e8-6e264ff05093")]
            public virtual ModuleLibraryRepositoryFolders.Register_panelsFolder Register_panels
            {
                get { return _register_panels; }
            }

            /// <summary>
            /// The Test_database_panel folder.
            /// </summary>
            [RepositoryFolder("fd5d1fb1-0360-4908-892a-e0422de48578")]
            public virtual ModuleLibraryRepositoryFolders.Test_database_panelFolder Test_database_panel
            {
                get { return _test_database_panel; }
            }

            /// <summary>
            /// The Main_menu folder.
            /// </summary>
            [RepositoryFolder("8b7a412e-0acd-40f5-8e9e-06f420ecc5b0")]
            public virtual ModuleLibraryRepositoryFolders.Main_menuFolder Main_menu
            {
                get { return _main_menu; }
            }
        }

        /// <summary>
        /// The Register_panelsFolder folder.
        /// </summary>
        [RepositoryFolder("9b9f04c1-9c82-4ed5-b9e8-6e264ff05093")]
        public partial class Register_panelsFolder : RepoGenBaseFolder
        {
            RepoItemInfo _registerInfo;

            /// <summary>
            /// Creates a new Register_panels  folder.
            /// </summary>
            public Register_panelsFolder(RepoGenBaseFolder parentFolder) :
                    base("Register_panels", "", parentFolder, 0, null, false, "9b9f04c1-9c82-4ed5-b9e8-6e264ff05093", "")
            {
                _registerInfo = new RepoItemInfo(this, "Register", "?/?/tabpage[@accessiblename=$varRegister]", 30000, null, "6bd3d99d-1e43-4183-8e36-5c31c3f37978");
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("9b9f04c1-9c82-4ed5-b9e8-6e264ff05093")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Register item.
            /// </summary>
            [RepositoryItem("6bd3d99d-1e43-4183-8e36-5c31c3f37978")]
            public virtual Ranorex.TabPage Register
            {
                get
                {
                    return _registerInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The Register item info.
            /// </summary>
            [RepositoryItemInfo("6bd3d99d-1e43-4183-8e36-5c31c3f37978")]
            public virtual RepoItemInfo RegisterInfo
            {
                get
                {
                    return _registerInfo;
                }
            }
        }

        /// <summary>
        /// The Test_database_panelFolder folder.
        /// </summary>
        [RepositoryFolder("fd5d1fb1-0360-4908-892a-e0422de48578")]
        public partial class Test_database_panelFolder : RepoGenBaseFolder
        {
            ModuleLibraryRepositoryFolders.Form_fieldsFolder _form_fields;
            ModuleLibraryRepositoryFolders.ButtonsFolder _buttons;
            RepoItemInfo _lbldatabasecounterInfo;
            RepoItemInfo _firstlistitemInfo;

            /// <summary>
            /// Creates a new Test_database_panel  folder.
            /// </summary>
            public Test_database_panelFolder(RepoGenBaseFolder parentFolder) :
                    base("Test_database_panel", "?/?/tabpage[@controlname='RxTabStandard']", parentFolder, 30000, null, false, "fd5d1fb1-0360-4908-892a-e0422de48578", "")
            {
                _form_fields = new ModuleLibraryRepositoryFolders.Form_fieldsFolder(this);
                _buttons = new ModuleLibraryRepositoryFolders.ButtonsFolder(this);
                _lbldatabasecounterInfo = new RepoItemInfo(this, "LblDatabaseCounter", "text[@controlname='lblNumberOfPersonsNumber']", 30000, null, "5f335bbe-a2ae-4998-a0f8-48848ec6653e");
                _firstlistitemInfo = new RepoItemInfo(this, "FirstListItem", "list[@controlname='lstPersonList']/?/?/listitem[1]", 30000, null, "44f4a067-7018-405b-8ad1-101690ed329c");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("fd5d1fb1-0360-4908-892a-e0422de48578")]
            public virtual Ranorex.TabPage Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("fd5d1fb1-0360-4908-892a-e0422de48578")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The LblDatabaseCounter item.
            /// </summary>
            [RepositoryItem("5f335bbe-a2ae-4998-a0f8-48848ec6653e")]
            public virtual Ranorex.Text LblDatabaseCounter
            {
                get
                {
                    return _lbldatabasecounterInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The LblDatabaseCounter item info.
            /// </summary>
            [RepositoryItemInfo("5f335bbe-a2ae-4998-a0f8-48848ec6653e")]
            public virtual RepoItemInfo LblDatabaseCounterInfo
            {
                get
                {
                    return _lbldatabasecounterInfo;
                }
            }

            /// <summary>
            /// The FirstListItem item.
            /// </summary>
            [RepositoryItem("44f4a067-7018-405b-8ad1-101690ed329c")]
            public virtual Ranorex.ListItem FirstListItem
            {
                get
                {
                    return _firstlistitemInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The FirstListItem item info.
            /// </summary>
            [RepositoryItemInfo("44f4a067-7018-405b-8ad1-101690ed329c")]
            public virtual RepoItemInfo FirstListItemInfo
            {
                get
                {
                    return _firstlistitemInfo;
                }
            }

            /// <summary>
            /// The Form_fields folder.
            /// </summary>
            [RepositoryFolder("18772a63-a2ed-4eff-9b74-3afe077a6c75")]
            public virtual ModuleLibraryRepositoryFolders.Form_fieldsFolder Form_fields
            {
                get { return _form_fields; }
            }

            /// <summary>
            /// The Buttons folder.
            /// </summary>
            [RepositoryFolder("360d1fb4-4126-43b4-afdf-971f5a297c1b")]
            public virtual ModuleLibraryRepositoryFolders.ButtonsFolder Buttons
            {
                get { return _buttons; }
            }
        }

        /// <summary>
        /// The Form_fieldsFolder folder.
        /// </summary>
        [RepositoryFolder("18772a63-a2ed-4eff-9b74-3afe077a6c75")]
        public partial class Form_fieldsFolder : RepoGenBaseFolder
        {
            RepoItemInfo _txtfirstnameInfo;
            RepoItemInfo _txtlastnameInfo;
            RepoItemInfo _txtageInfo;
            RepoItemInfo _rdbgenderInfo;

            /// <summary>
            /// Creates a new Form_fields  folder.
            /// </summary>
            public Form_fieldsFolder(RepoGenBaseFolder parentFolder) :
                    base("Form_fields", "", parentFolder, 0, null, false, "18772a63-a2ed-4eff-9b74-3afe077a6c75", "")
            {
                _txtfirstnameInfo = new RepoItemInfo(this, "TxtFirstName", "?/?/text[@accessiblename='First name']", 30000, null, "bf899d72-4698-4f59-b8ae-64917e4c6cad");
                _txtlastnameInfo = new RepoItemInfo(this, "TxtLastName", "?/?/text[@accessiblename='Last name']", 30000, null, "84b60263-0dc0-412c-9c91-be81763c93bc");
                _txtageInfo = new RepoItemInfo(this, "TxtAge", "?/?/text[@controlname='upDownEdit']", 30000, null, "f93c82f4-3859-42a8-be5f-5f19f2a6ab9f");
                _rdbgenderInfo = new RepoItemInfo(this, "RdbGender", "?/?/radiobutton[@controltext=$varGender]", 30000, null, "2c4264ea-5472-4130-914d-0c2204007626");
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("18772a63-a2ed-4eff-9b74-3afe077a6c75")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The TxtFirstName item.
            /// </summary>
            [RepositoryItem("bf899d72-4698-4f59-b8ae-64917e4c6cad")]
            public virtual Ranorex.Text TxtFirstName
            {
                get
                {
                    return _txtfirstnameInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The TxtFirstName item info.
            /// </summary>
            [RepositoryItemInfo("bf899d72-4698-4f59-b8ae-64917e4c6cad")]
            public virtual RepoItemInfo TxtFirstNameInfo
            {
                get
                {
                    return _txtfirstnameInfo;
                }
            }

            /// <summary>
            /// The TxtLastName item.
            /// </summary>
            [RepositoryItem("84b60263-0dc0-412c-9c91-be81763c93bc")]
            public virtual Ranorex.Text TxtLastName
            {
                get
                {
                    return _txtlastnameInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The TxtLastName item info.
            /// </summary>
            [RepositoryItemInfo("84b60263-0dc0-412c-9c91-be81763c93bc")]
            public virtual RepoItemInfo TxtLastNameInfo
            {
                get
                {
                    return _txtlastnameInfo;
                }
            }

            /// <summary>
            /// The TxtAge item.
            /// </summary>
            [RepositoryItem("f93c82f4-3859-42a8-be5f-5f19f2a6ab9f")]
            public virtual Ranorex.Text TxtAge
            {
                get
                {
                    return _txtageInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The TxtAge item info.
            /// </summary>
            [RepositoryItemInfo("f93c82f4-3859-42a8-be5f-5f19f2a6ab9f")]
            public virtual RepoItemInfo TxtAgeInfo
            {
                get
                {
                    return _txtageInfo;
                }
            }

            /// <summary>
            /// The RdbGender item.
            /// </summary>
            [RepositoryItem("2c4264ea-5472-4130-914d-0c2204007626")]
            public virtual Ranorex.RadioButton RdbGender
            {
                get
                {
                    return _rdbgenderInfo.CreateAdapter<Ranorex.RadioButton>(true);
                }
            }

            /// <summary>
            /// The RdbGender item info.
            /// </summary>
            [RepositoryItemInfo("2c4264ea-5472-4130-914d-0c2204007626")]
            public virtual RepoItemInfo RdbGenderInfo
            {
                get
                {
                    return _rdbgenderInfo;
                }
            }
        }

        /// <summary>
        /// The ButtonsFolder folder.
        /// </summary>
        [RepositoryFolder("360d1fb4-4126-43b4-afdf-971f5a297c1b")]
        public partial class ButtonsFolder : RepoGenBaseFolder
        {
            RepoItemInfo _btnopendepartmentlistInfo;
            RepoItemInfo _btnaddentryInfo;
            RepoItemInfo _btnremoveentryInfo;

            /// <summary>
            /// Creates a new Buttons  folder.
            /// </summary>
            public ButtonsFolder(RepoGenBaseFolder parentFolder) :
                    base("Buttons", "", parentFolder, 0, null, false, "360d1fb4-4126-43b4-afdf-971f5a297c1b", "")
            {
                _btnopendepartmentlistInfo = new RepoItemInfo(this, "BtnOpenDepartmentList", "?/?/button[@accessiblename='Open']", 30000, null, "bf7e3be5-8e14-442c-b63e-0efad96ca2f9");
                _btnaddentryInfo = new RepoItemInfo(this, "BtnAddEntry", "button[@controlname='btnAddPerson']", 30000, null, "d4f5e7fb-e478-49ef-9175-57220881b34c");
                _btnremoveentryInfo = new RepoItemInfo(this, "BtnRemoveEntry", "button[@controlname='btnDeletePerson']", 30000, null, "04d109e1-7ea9-4c0b-9581-7bc87b3feacf");
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("360d1fb4-4126-43b4-afdf-971f5a297c1b")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The BtnOpenDepartmentList item.
            /// </summary>
            [RepositoryItem("bf7e3be5-8e14-442c-b63e-0efad96ca2f9")]
            public virtual Ranorex.Button BtnOpenDepartmentList
            {
                get
                {
                    return _btnopendepartmentlistInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The BtnOpenDepartmentList item info.
            /// </summary>
            [RepositoryItemInfo("bf7e3be5-8e14-442c-b63e-0efad96ca2f9")]
            public virtual RepoItemInfo BtnOpenDepartmentListInfo
            {
                get
                {
                    return _btnopendepartmentlistInfo;
                }
            }

            /// <summary>
            /// The BtnAddEntry item.
            /// </summary>
            [RepositoryItem("d4f5e7fb-e478-49ef-9175-57220881b34c")]
            public virtual Ranorex.Button BtnAddEntry
            {
                get
                {
                    return _btnaddentryInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The BtnAddEntry item info.
            /// </summary>
            [RepositoryItemInfo("d4f5e7fb-e478-49ef-9175-57220881b34c")]
            public virtual RepoItemInfo BtnAddEntryInfo
            {
                get
                {
                    return _btnaddentryInfo;
                }
            }

            /// <summary>
            /// The BtnRemoveEntry item.
            /// </summary>
            [RepositoryItem("04d109e1-7ea9-4c0b-9581-7bc87b3feacf")]
            public virtual Ranorex.Button BtnRemoveEntry
            {
                get
                {
                    return _btnremoveentryInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The BtnRemoveEntry item info.
            /// </summary>
            [RepositoryItemInfo("04d109e1-7ea9-4c0b-9581-7bc87b3feacf")]
            public virtual RepoItemInfo BtnRemoveEntryInfo
            {
                get
                {
                    return _btnremoveentryInfo;
                }
            }
        }

        /// <summary>
        /// The Main_menuFolder folder.
        /// </summary>
        [RepositoryFolder("8b7a412e-0acd-40f5-8e9e-06f420ecc5b0")]
        public partial class Main_menuFolder : RepoGenBaseFolder
        {
            RepoItemInfo _mnuaboutInfo;
            RepoItemInfo _mnuinfoInfo;

            /// <summary>
            /// Creates a new Main_menu  folder.
            /// </summary>
            public Main_menuFolder(RepoGenBaseFolder parentFolder) :
                    base("Main_menu", "", parentFolder, 30000, null, false, "8b7a412e-0acd-40f5-8e9e-06f420ecc5b0", "")
            {
                _mnuaboutInfo = new RepoItemInfo(this, "MnuAbout", "?/?/menuitem[@accessiblename='About']", 30000, null, "31945725-c1c1-48d7-b5c6-8631ff075e3d");
                _mnuinfoInfo = new RepoItemInfo(this, "MnuInfo", "?/?/menuitem[@accessiblename='Info']", 30000, null, "9f424378-b01c-4911-806c-ae8ceb4ff9a9");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("8b7a412e-0acd-40f5-8e9e-06f420ecc5b0")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("8b7a412e-0acd-40f5-8e9e-06f420ecc5b0")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The MnuAbout item.
            /// </summary>
            [RepositoryItem("31945725-c1c1-48d7-b5c6-8631ff075e3d")]
            public virtual Ranorex.MenuItem MnuAbout
            {
                get
                {
                    return _mnuaboutInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The MnuAbout item info.
            /// </summary>
            [RepositoryItemInfo("31945725-c1c1-48d7-b5c6-8631ff075e3d")]
            public virtual RepoItemInfo MnuAboutInfo
            {
                get
                {
                    return _mnuaboutInfo;
                }
            }

            /// <summary>
            /// The MnuInfo item.
            /// </summary>
            [RepositoryItem("9f424378-b01c-4911-806c-ae8ceb4ff9a9")]
            public virtual Ranorex.MenuItem MnuInfo
            {
                get
                {
                    return _mnuinfoInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The MnuInfo item info.
            /// </summary>
            [RepositoryItemInfo("9f424378-b01c-4911-806c-ae8ceb4ff9a9")]
            public virtual RepoItemInfo MnuInfoInfo
            {
                get
                {
                    return _mnuinfoInfo;
                }
            }
        }

        /// <summary>
        /// The DepartmentListAppFolder folder.
        /// </summary>
        [RepositoryFolder("09bcc6f7-9fe6-4896-b1c9-7dd8d01b68ac")]
        public partial class DepartmentListAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _departmentitemInfo;

            /// <summary>
            /// Creates a new DepartmentList  folder.
            /// </summary>
            public DepartmentListAppFolder(RepoGenBaseFolder parentFolder) :
                    base("DepartmentList", "/list[@controlid='1000']", parentFolder, 30000, null, true, "09bcc6f7-9fe6-4896-b1c9-7dd8d01b68ac", "")
            {
                _departmentitemInfo = new RepoItemInfo(this, "DepartmentItem", "listitem[@text=$varDepartment]", 30000, null, "5a6f280d-673b-4669-88ef-8464fe9f039e");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("09bcc6f7-9fe6-4896-b1c9-7dd8d01b68ac")]
            public virtual Ranorex.List Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.List>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("09bcc6f7-9fe6-4896-b1c9-7dd8d01b68ac")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The DepartmentItem item.
            /// </summary>
            [RepositoryItem("5a6f280d-673b-4669-88ef-8464fe9f039e")]
            public virtual Ranorex.ListItem DepartmentItem
            {
                get
                {
                    return _departmentitemInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The DepartmentItem item info.
            /// </summary>
            [RepositoryItemInfo("5a6f280d-673b-4669-88ef-8464fe9f039e")]
            public virtual RepoItemInfo DepartmentItemInfo
            {
                get
                {
                    return _departmentitemInfo;
                }
            }
        }

        /// <summary>
        /// The RxDemoAppAboutInfoAppFolder folder.
        /// </summary>
        [RepositoryFolder("3b5e59b2-3bcc-4a32-a4aa-281bb2c188b0")]
        public partial class RxDemoAppAboutInfoAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _lblaboutinfoInfo;

            /// <summary>
            /// Creates a new RxDemoAppAboutInfo  folder.
            /// </summary>
            public RxDemoAppAboutInfoAppFolder(RepoGenBaseFolder parentFolder) :
                    base("RxDemoAppAboutInfo", "/form[@title='']", parentFolder, 30000, null, true, "3b5e59b2-3bcc-4a32-a4aa-281bb2c188b0", "")
            {
                _lblaboutinfoInfo = new RepoItemInfo(this, "LblAboutInfo", "text[@controlid='65535']", 30000, null, "d8d9add9-1f31-4f9c-a090-44ed0976c639");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("3b5e59b2-3bcc-4a32-a4aa-281bb2c188b0")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("3b5e59b2-3bcc-4a32-a4aa-281bb2c188b0")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The LblAboutInfo item.
            /// </summary>
            [RepositoryItem("d8d9add9-1f31-4f9c-a090-44ed0976c639")]
            public virtual Ranorex.Text LblAboutInfo
            {
                get
                {
                    return _lblaboutinfoInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The LblAboutInfo item info.
            /// </summary>
            [RepositoryItemInfo("d8d9add9-1f31-4f9c-a090-44ed0976c639")]
            public virtual RepoItemInfo LblAboutInfoInfo
            {
                get
                {
                    return _lblaboutinfoInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
