///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace DatabaseTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the DatabaseTestRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("e4a90dc0-334f-41f6-b304-57d240b1fbdf")]
    public partial class DatabaseTestRepository : RepoGenBaseFolder
    {
        static DatabaseTestRepository instance = new DatabaseTestRepository();

        /// <summary>
        /// Gets the singleton class instance representing the DatabaseTestRepository element repository.
        /// </summary>
        [RepositoryFolder("e4a90dc0-334f-41f6-b304-57d240b1fbdf")]
        public static DatabaseTestRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public DatabaseTestRepository() 
            : base("DatabaseTestRepository", "/", null, 0, false, "e4a90dc0-334f-41f6-b304-57d240b1fbdf", ".\\RepositoryImages\\DatabaseTestRepositorye4a90dc0.rximgres")
        {
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("e4a90dc0-334f-41f6-b304-57d240b1fbdf")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class DatabaseTestRepositoryFolders
    {
    }
#pragma warning restore 0436
}
