///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace ModuleLibrary.Recording_modules.Navigation
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The SelectRegister recording.
    /// </summary>
    [TestModule("cda888a9-9cc0-436e-9289-55cc1f987cde", ModuleType.Recording, 1)]
    public partial class SelectRegister : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::ModuleLibrary.ModuleLibraryRepository repository.
        /// </summary>
        public static global::ModuleLibrary.ModuleLibraryRepository repo = global::ModuleLibrary.ModuleLibraryRepository.Instance;

        static SelectRegister instance = new SelectRegister();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public SelectRegister()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static SelectRegister Instance
        {
            get { return instance; }
        }

#region Variables

        /// <summary>
        /// Gets or sets the value of variable varRegister.
        /// </summary>
        [TestVariable("1494ba44-4ec7-43fb-be5a-9042db4cda73")]
        public string varRegister
        {
            get { return repo.varRegister; }
            set { repo.varRegister = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 0;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 0.00;

            Init();

            // Parametrized selection of register panel; Selection of register based on value of parameter
            Report.Log(ReportLevel.Info, "Mouse", "Parametrized selection of register panel; Selection of register based on value of parameter\r\nMouse Left Click item 'RXDemoApplication.Register_panels.Register' at Center.", repo.RXDemoApplication.Register_panels.RegisterInfo, new RecordItemIndex(0));
            repo.RXDemoApplication.Register_panels.Register.Click();
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
